### ISSUE TITLE
生成硬链接的另一种方式

### ISSUE THREAD

**Issue by xuewenG** [backtracker/link_tool#1]
首先说明一下，我**无意冒犯**您的工作成果，这里只是提供另外一种思路。

生成硬链接的方式对整理资源和做种真的很有用，您写的这个脚本的效果很好。

我想分享一下生成硬链接的另一种方式：可以使用 Linux 系统自带的 `cp` 工具来生成硬链接。
```shell
cp -r -l [src_dir] [dst_dir]
```
我已经测试过可以使用了：

![cp](https://user-images.githubusercontent.com/32838722/76926658-db24ae80-6917-11ea-941c-f5354185ee61.png)

**Comment by backtracker** [comment]
> 首先说明一下，我**无意冒犯**您的工作成果，这里只是提供另外一种思路。
> 
> 生成硬链接的方式对整理资源和做种真的很有用，您写的这个脚本的效果很好。
> 
> 我想分享一下生成硬链接的另一种方式：可以使用 Linux 系统自带的 `cp` 工具来生成硬链接。
> 
> ```shell
> cp -r -l [src_dir] [dst_dir]
> ```
> 
> 我已经测试过可以使用了：
> 
> ![cp](https://user-images.githubusercontent.com/32838722/76926658-db24ae80-6917-11ea-941c-f5354185ee61.png)

我试了一下，真的有用。inode是一样的。多谢分享了啊。我这个项目貌似可以关了，哈哈哈
